@startuml
' Style definitions
skinparam componentStyle uml2
skinparam component {
    BackgroundColor #2C5773
    FontColor white
    BorderColor Black
}

package "Input" {
    [User Query] as user_query
    [Camera Feed] as camera_feed
    [Microphone Input] as microphone_input
    [Position Data] as position_data
}

package "Outside World" as world {
    [Gazebo Simulation] as gazebo
    [Real-World Environment] as real_world
}

package "Goat Planner" {
    component "Shepherd" as shepherd
    [Goat behavior (BT)] as goat_behavior
    [Plan Server] as plan_server
    [Whisper] as whisper
    [Ollama (Custom Model)] as ollama
    [Goat Controller] as goat_controller
    [Flask Server] as flask_server
}

package "Web application" {
    component "React Client" as frontend_node
}


package "Output" {
    [Robot Actions] as robot_actions
    [TTS] as tts
}

' Connections between components

' Input
world -d-> camera_feed
world -d-> microphone_input
world -d-> position_data
camera_feed --> shepherd
microphone_input --> whisper
position_data --> shepherd
frontend_node --> user_query : user interface

' Processing
shepherd <--> goat_controller : send object context
goat_behavior <--> goat_controller : send action context
plan_server <--> goat_controller : give plan
whisper <--> goat_controller
ollama <--> goat_controller
tts <--> goat_controller
goat_controller --> flask_server : give plan
flask_server --> frontend_node : transmits plan and chat updates

' Output
goat_behavior --> robot_actions : execute task

@enduml
